export interface DemoService { title: string; description: string; icon: string; }
export interface DemoTestimonial { name: string; text: string; role: string; rating: number; }
export interface DemoNavLink { label: string; href: string; }
export interface DemoStats { years: string; clients: string; team: string; rating: string; }
export interface DemoData {
  slug: string; companyName: string; tagline: string; primaryColor: string; secondaryColor: string;
  heroTitle: string; heroSubtitle: string; heroCta: string;
  aboutTitle: string; aboutText: string;
  services: DemoService[]; testimonials: DemoTestimonial[];
  phone: string; whatsapp: string; address: string; email: string;
  navLinks: DemoNavLink[]; stats: DemoStats;
}

export const demosData: Record<string, DemoData> = {
  "saude-clean": {
    slug: "saude-clean", companyName: "Clínica Odonto Vita", tagline: "Sorriso bonito não é luxo — é saúde",
    primaryColor: "#4A90D9", secondaryColor: "#FFFFFF",
    heroTitle: "Vergonha de sorrir? Nunca mais.", heroSubtitle: "Você merece um sorriso que abre portas. Implantes que parecem dentes naturais, clareamento que brilha de verdade e ortodontia invisível que ninguém percebe. Tudo em um só lugar, com profissionais que respeitam seu tempo e seu bolso.", heroCta: "Agendar pelo WhatsApp",
    aboutTitle: "Por que 3.500+ pacientes confiam na Odonto Vita", aboutText: "Dente dói é dor que ninguém merece. Há 18 anos a gente tira essa dor e devolve o sorriso — com clareamento que funciona de verdade, implantes que duram décadas e aparelhos invisíveis que não atrapalham sua vida. Sem surpresa na hora de pagar, sem fila infinita, sem atendente robótica. Você chega, é bem recebido, e sai sorrindo. Simples assim.",
    services: [
      { title: "Clareamento Dental", description: "Seus dentes brancos em 1 hora. Resultado visível na primeira sessão — sem sensibilidade, sem dor. Tecnologia LED de última geração.", icon: "Sparkles" },
      { title: "Implante Dentário", description: "Dente fixo que parece natural de verdade. Titânio de altíssima qualidade com garantia de 10 anos. Volte a comer o que quiser.", icon: "Shield" },
      { title: "Ortodontia Invisível", description: "Alinhe transparente que endireita seus dentes sem ninguém notar. Sem fio, sem metal, sem constrangimento. Invisalign autorizado.", icon: "Smile" },
      { title: "Limpeza Profunda", description: "Prevenir é mais barato que remediar. Remoção de tártaro, orientação personalizada e saúde bucal garantida. Preço acessível.", icon: "Heart" },
    ],
    testimonials: [
      { name: "Maria Fernanda S.", text: "Eu tinha tanto medo de dentista que deixei meu dente apodrecer. Na Odonto Vita, me senti em casa. Fiz o implante e hoje como carne com osso sem medo. Chorei de felicidade.", role: "Fez implante há 3 anos", rating: 5 },
      { name: "Carlos Eduardo R.", text: "Fiz clareamento antes do meu casamento. Meu sorriso nas fotos ficou absurdo. Melhor investimento que fiz. O preço foi justo e o resultado durou.", role: "Fez clareamento há 2 anos", rating: 5 },
      { name: "Ana Paula M.", text: "Aparelho invisível foi a melhor decisão. Tenho 35 anos e não ia colocar ferro na boca. Ninguém nunca percebeu e meu sorriso ficou perfeito em 10 meses.", role: "Fez Invisalign há 1 ano", rating: 5 },
    ],
    phone: "(11) 3456-7890", whatsapp: "5511910376040", address: "Av. Paulista, 1578 - Bela Vista, São Paulo - SP", email: "contato@odontovita.com.br",
    navLinks: [{ label: "Início", href: "#" }, { label: "Sobre", href: "#sobre" }, { label: "Tratamentos", href: "#servicos" }, { label: "Depoimentos", href: "#depoimentos" }, { label: "Contato", href: "#contato" }],
    stats: { years: "18+", clients: "3.500+", team: "12", rating: "4.9" },
  },
  "saude-premium": {
    slug: "saude-premium", companyName: "Instituto Bem Viver", tagline: "Sua mente não pode esperar",
    primaryColor: "#5B8DB8", secondaryColor: "#F0F4F8",
    heroTitle: "A ansiedade não vai passar sozinha.", heroSubtitle: "Você já tentou de tudo: meditação, chá, respirar fundo. Nada funcionou de verdade. Na Bem Viver, a gente vai na raiz do problema — com terapia que funciona de verdade e profissionais que entendem o que você sente.", heroCta: "Agendar Sessão",
    aboutTitle: "Terapia que funciona de verdade", aboutText: "Chegar cansado no consultório e sair sem saber por quê não é terapia — é conversa fiada. Aqui, cada sessão tem direção. Usamos TCC, psicanálise e mindfulness com um objetivo: você sentir melhora real nas primeiras semanas. Não tem julgamento, não tem receita pronta. Tem escuta de verdade e técnica que funciona.",
    services: [
      { title: "Terapia Individual", description: "Sessões focadas no SEU problema. TCC para ansiedade, psicanálise para autoconhecimento. Você sente diferença nas primeiras semanas.", icon: "User" },
      { title: "Terapia de Casal", description: "Vocês brigam pelo mesmo assunto toda semana? A gente ensina a se comunicar de verdade. Não é mágica — é técnica.", icon: "Heart" },
      { title: "Grupo de Apoio", description: "Ansiedade, luto, pós-parto. Compartilhar com quem vive a mesma coisa alivia como nada mais alivia. Grupos fechados e seguros.", icon: "Users" },
      { title: "Avaliação Psicológica", description: "Laudo completo para processos jurídicos, adaptação de provas ou autoconhecimento. Testes validados e relatório claro.", icon: "Clipboard" },
    ],
    testimonials: [
      { name: "Juliana T.", text: "Tomei remédio pra ansiedade 6 anos e não melhorava. Em 3 meses de terapia aqui, reduzi metade da dose. Pela primeira vez sinto que tô no caminho certo.", role: "Em terapia há 2 anos", rating: 5 },
      { name: "Roberto e Camila", text: "A gente tava a um passo do divórcio. A terapia de casal nos ensinou a brigar menos e a se ouvir mais. Parece outro casamento.", role: "Em terapia há 1 ano", rating: 5 },
      { name: "Fernanda L.", text: "O grupo de mulheres com ansiedade mudou minha vida. Ouvir alguém falar exatamente o que eu sinto... não tem preço. Me sinto menos sozinha.", role: "Participante há 8 meses", rating: 5 },
    ],
    phone: "(11) 3234-5678", whatsapp: "5511910376040", address: "Rua Oscar Freire, 890 - Pinheiros, São Paulo - SP", email: "contato@institutobemviver.com.br",
    navLinks: [{ label: "Início", href: "#" }, { label: "Sobre", href: "#sobre" }, { label: "Especialidades", href: "#servicos" }, { label: "Depoimentos", href: "#depoimentos" }, { label: "Contato", href: "#contato" }],
    stats: { years: "6+", clients: "1.200+", team: "8", rating: "4.8" },
  },
  "beleza-moderno": {
    slug: "beleza-moderno", companyName: "Studio Noir", tagline: "Entra aí e sai outra pessoa",
    primaryColor: "#1A1A1A", secondaryColor: "#D4AF37",
    heroTitle: "Seu cabelo é a primeira coisa que notam em você.", heroSubtitle: "Corte que combina com seu rosto. Coloração que dura. Barba na medida. No Studio Noir, cada cliente é um projeto — e o resultado fala mais alto que qualquer propaganda.", heroCta: "Reservar Horário",
    aboutTitle: "Por que o Studio Noir é diferente", aboutText: "Salão que faz tudo igual não é pra gente. Aqui, antes de cortar um fio, a gente entende seu estilo, sua rotina, o que você quer passar pro mundo. Usamos produto premium, técnica atualizada e muita vontade de ver você sair de lá se olhando no espelho e gostar do que vê. É isso que nos move há 8 anos.",
    services: [
      { title: "Corte Personalizado", description: "Não tem isso de 'corte masculino padrão'. A gente analisa seu rosto, seu cabelo e sua vida. Corte que funciona de verdade no dia a dia.", icon: "Scissors" },
      { title: "Coloração Artística", description: "Balayage que parece natural, mechas que iluminam seu rosto. Produto premium que não estraga o fio e cor que dura meses.", icon: "Palette" },
      { title: "Tratamento Capilar", description: "Cabelo seco, quebradiço, sem vida? Hidratação profunda, reconstrução e cauterização com resultado visível na primeira vez.", icon: "Sparkles" },
      { title: "Barbearia Premium", description: "Barba na navalha, toalha quente, produto pra pele. Momento seu que ninguém tira. Ambiente exclusivo pra quem leva a sério.", icon: "Award" },
    ],
    testimonials: [
      { name: "Luana P.", text: "Meu balayage ficou ABSURDO. Todo mundo pergunta onde fiz. O cuidado com o fio é outro nível — 3 meses e a cor continua linda.", role: "Cliente há 3 anos", rating: 5 },
      { name: "Thiago M.", text: "A barbearia é outra coisa. Toalha quente, navalha, produto bom. É o melhor momento da minha semana. O corte dura.", role: "Cliente há 2 anos", rating: 5 },
      { name: "Isabela C.", text: "Sempre saio de lá me sentindo PODEROSA. Eles realmente entendem o que funciona pra cada pessoa. Nunca me decepcionaram.", role: "Cliente há 1 ano", rating: 5 },
    ],
    phone: "(11) 3789-0123", whatsapp: "5511910376040", address: "Rua Augusta, 2345 - Consolação, São Paulo - SP", email: "contato@studionoir.com.br",
    navLinks: [{ label: "Início", href: "#" }, { label: "Sobre", href: "#sobre" }, { label: "Serviços", href: "#servicos" }, { label: "Depoimentos", href: "#depoimentos" }, { label: "Contato", href: "#contato" }],
    stats: { years: "8+", clients: "2.800+", team: "15", rating: "4.9" },
  },
  "beleza-feminino": {
    slug: "beleza-feminino", companyName: "Rosa & Cia", tagline: "Sua beleza sem filtro",
    primaryColor: "#C4727F", secondaryColor: "#F5E6CC",
    heroTitle: "Quem disse que você precisa de maquiagem pra se achar bonita?", heroSubtitle: "Tratamentos que fazem sua pele brilhar de verdade. Depilação definitiva que libera seu tempo. Procedimentos que realçam o que você já tem — sem parecer outra pessoa, sem exagero.", heroCta: "Agendar Avaliação Grátis",
    aboutTitle: "Beleza de verdade, sem filtro", aboutText: "A gente não vende padrão inalcançável. A Rosa & Cia existe pra mulher que quer se sentir bem na própria pele — sem precisar de app nem maquiagem pesada. Nossos tratamentos são pensados pra resultados naturais: pele que brilha, corpo que você reconhece, autoestima que sobe. Tecnologia de ponta com acolhimento de verdade.",
    services: [
      { title: "Tratamentos Faciais", description: "Peeling, microagulhamento e lifting sem cirurgia. Pele lisa, iluminada, sem poro. Resultado visível em 3 sessões ou devolvemos seu dinheiro.", icon: "Sparkles" },
      { title: "Depilação a Laser", description: "Diodo laser de última geração. Acaba com o pelo, não com sua pele. 6 sessões e você nunca mais gasta tempo depilando.", icon: "Zap" },
      { title: "Massagem Modeladora", description: "Reduz medidas e combate celulite com técnica, não com milagre. Resultado real em poucas sessões. Você sente e mede a diferença.", icon: "Heart" },
      { title: "Design de Sobrancelhas", description: "Sobrancelha muda o rosto inteiro. Design personalizado com henna e micropigmentação. Acorda bonita todo dia.", icon: "Eye" },
    ],
    testimonials: [
      { name: "Patricia R.", text: "Eu usava base TODO DIA há 10 anos. Depois do peeling, saio de casa sem maquiagem e me sinto linda. Nunca pensei que ia chegar nesse ponto.", role: "Cliente há 2 anos", rating: 5 },
      { name: "Camila S.", text: "A depilação a laser foi a melhor decisão da minha vida. 4 meses e já não preciso me depilar. Liberdade pura. Dinheiro bem gasto.", role: "Cliente há 1 ano", rating: 5 },
      { name: "Regina A.", text: "Eu achava que massagem modeladora era golpe. Em 5 sessões, perdi 4cm de barriga. Medido e comprovado. Voltei pra mais.", role: "Cliente há 8 meses", rating: 5 },
    ],
    phone: "(11) 3456-7891", whatsapp: "5511910376040", address: "Rua Haddock Lobo, 1234 - Cerqueira César, São Paulo - SP", email: "contato@rosacia.com.br",
    navLinks: [{ label: "Início", href: "#" }, { label: "Sobre", href: "#sobre" }, { label: "Tratamentos", href: "#servicos" }, { label: "Depoimentos", href: "#depoimentos" }, { label: "Contato", href: "#contato" }],
    stats: { years: "5+", clients: "1.500+", team: "6", rating: "4.8" },
  },
  "auto-bold": {
    slug: "auto-bold", companyName: "Garage 55", tagline: "Mecânico honesto existe — é aqui",
    primaryColor: "#FF6B00", secondaryColor: "#1A1A1A",
    heroTitle: "Cansou de levar susto na oficina?", heroSubtitle: "Orçamento surpresa, peça que 'precisava' trocar, prazo que nunca cumpre. Na Garage 55, você aprova o orçamento antes de qualquer serviço. Peça original, mecânico certificado e garantia de 12 meses. Transparência que nenhuma outra oficina tem coragem de ter.", heroCta: "Pedir Orçamento Grátis",
    aboutTitle: "Oficina que você confia de olhos fechados", aboutText: "A gente sabe: levar o carro na oficina é ansiedade pura. Você não entende de mecânica e fica na mão do primeiro que aparece. Há 22 anos a Garage 55 existe pra acabar com isso. Orçamento detalhado que você aprova, fotos do que tá sendo feito, peças com procedência e garantia de 12 meses em tudo. Você acompanha cada etapa pelo WhatsApp. Sem surpresa, sem estresse.",
    services: [
      { title: "Revisão Completa", description: "40 pontos verificados com laudo fotográfico. Você vê TUDO que tá bom e o que precisa trocar. Sem achismo, sem inventar problema.", icon: "Wrench" },
      { title: "Diagnóstico Eletrônico", description: "Luzinha acesa no painel? Scanner de última geração lê a falha na hora. Você sabe exatamente o que tá errado antes de aprovar qualquer coisa.", icon: "Monitor" },
      { title: "Troca de Óleo e Filtros", description: "Óleo e filtro original ou premium. Coletamos e entregamos seu carro. Manutenção em dia sem você sair de casa ou do trabalho.", icon: "Droplet" },
      { title: "Freios e Suspensão", description: "Freio é vida — não dá pra economizar. Pastilha, disco, amortecedor: peça boa, mão de obra certeira. Seu carro para quando você manda.", icon: "Shield" },
    ],
    testimonials: [
      { name: "Marcos V.", text: "Levo meu carro aqui há 10 anos. Uma vez achei que ia gastar 3 mil. O laudo mostrou que só precisava de 800. Honestidade que não existe em outro lugar.", role: "Cliente há 10 anos", rating: 5 },
      { name: "Adriana K.", text: "Três oficinas não acharam o problema do meu carro. Na Garage 55, em 2 horas já tinham o diagnóstico e o preço. Resolveram no mesmo dia. Choro.", role: "Cliente há 3 anos", rating: 5 },
      { name: "Paulo H.", text: "Mando foto do orçamento pro meu mecânico de confiança e ele fala: 'tá justo, pode fazer'. Esse mecânico de confiança é a Garage 55.", role: "Cliente há 5 anos", rating: 5 },
    ],
    phone: "(11) 3890-1234", whatsapp: "5511910376040", address: "Rua Vergueiro, 3456 - Vila Mariana, São Paulo - SP", email: "contato@garage55.com.br",
    navLinks: [{ label: "Início", href: "#" }, { label: "Sobre", href: "#sobre" }, { label: "Serviços", href: "#servicos" }, { label: "Depoimentos", href: "#depoimentos" }, { label: "Contato", href: "#contato" }],
    stats: { years: "22+", clients: "4.000+", team: "10", rating: "4.9" },
  },
  "auto-tecnico": {
    slug: "auto-tecnico", companyName: "TechAuto", tagline: "Seu carro com tecnologia de verdade",
    primaryColor: "#3B82F6", secondaryColor: "#374151",
    heroTitle: "Seu som automotivo tá uma merda? A gente resolve.", heroSubtitle: "Instalação profissional que parece de fábrica. Alarme que realmente protege. Multimídia que funciona. Câmera de ré que você enxerga de verdade. Aqui, cada fio no lugar e cada parafuso apertado.", heroCta: "Solicitar Orçamento",
    aboutTitle: "Instalação que parece original — porque é feita direito", aboutText: "Aquele som que chiando, alarme que dispara sozinho, câmera de ré que mostra mais chuva que carro? Isso é instalação mal feita. Na TechAuto, cada serviço é feito como se fosse pro nosso próprio carro. Fio escondido, conector original, acabamento impecável. Você nem lembra que foi instalado depois — porque funciona perfeitamente. Desde 2014 sem nenhuma reclamação no Procon.",
    services: [
      { title: "Som Automotivo", description: "Rádio, alto-falante, subwoofer e módulo. Projeto de áudio personalizado pro SEU carro. Som limpo que não distorce no volume alto.", icon: "Volume2" },
      { title: "Alarme e Rastreador", description: "Proteção real: rastreamento 24h no celular, bloqueio remoto e notificação instantânea. Seu carro onde você estiver.", icon: "Shield" },
      { title: "Multimídia e Câmera", description: "Central Android com Waze e Spotify, câmera de ré HD e sensor de estacionamento. Instalação limpa, sem fio aparente.", icon: "Monitor" },
      { title: "Iluminação LED", description: "Farol e lanterna em LED de alta potência. Enxerga 3x mais longe sem ofuscar. Instalação certificada, zero risco.", icon: "Lightbulb" },
    ],
    testimonials: [
      { name: "Ricardo F.", text: "O sistema de som que instalaram é OUTRO NÍVEL. Parece cinema dentro do carro. E a instalação é tão limpa que parece original de fábrica.", role: "Cliente há 2 anos", rating: 5 },
      { name: "Sandra M.", text: "Coloquei rastreador e alarme. Uma vez esqueci o carro na rua e o app avisou na hora que mexeram. Segurança que funciona de verdade.", role: "Cliente há 1 ano", rating: 5 },
      { name: "Diego A.", text: "Câmera de ré HD + sensor = nunca mais bati de ré. A instalação ficou invisível, parece que veio de fábrica. Preço justo demais.", role: "Cliente há 6 meses", rating: 5 },
    ],
    phone: "(11) 3901-2345", whatsapp: "5511910376040", address: "Av. Brigadeiro Faria Lima, 2345 - Itaim Bibi, São Paulo - SP", email: "contato@techauto.com.br",
    navLinks: [{ label: "Início", href: "#" }, { label: "Sobre", href: "#sobre" }, { label: "Serviços", href: "#servicos" }, { label: "Depoimentos", href: "#depoimentos" }, { label: "Contato", href: "#contato" }],
    stats: { years: "10+", clients: "2.200+", team: "8", rating: "4.8" },
  },
  "juridico-sobrio": {
    slug: "juridico-sobrio", companyName: "Advogados Associados Melo", tagline: "Direito que bate de frente",
    primaryColor: "#1B2A4A", secondaryColor: "#C9A84C",
    heroTitle: "Seus direitos não vão se defender sozinhos.", heroSubtitle: "Chefe te deve? Ex não paga pensão? Empresa te enganou? Na Melo Advogados, a gente não faz carta bonita — a gente briga pelo que é seu. 25 anos ganhando causas que outros desistiam.", heroCta: "Falar com Advogado Agora",
    aboutTitle: "Advocacia que briga — e ganha", aboutText: "Escritório de advocacia que não te enrola com juridiquês. Aqui, você entende cada passo do seu processo, sabe as chances reais de ganhar e acompanha tudo pelo WhatsApp. Há 25 anos atuamos nas áreas que mais impactam a vida das pessoas: trabalhista, civil, empresarial e família. Não prometemos milagre — prometemos dedicação e resultado.",
    services: [
      { title: "Direito Trabalhista", description: "Seu chefe te deve horas extras, verbas rescisórias ou te demitiu injustamente. A gente briga por cada centavo que é SEU por direito.", icon: "Briefcase" },
      { title: "Direito do Consumidor", description: "Produto veio com defeito e não trocam? Plano de saúde negou cobertura? A gente faz valer o Código de Defesa do Consumidor.", icon: "Scale" },
      { title: "Direito Empresarial", description: "Sócio que não cumpre, contrato furado, dívida que não recebia. Protegemos seu negócio com contrato bem feito e atuação firme.", icon: "Building" },
      { title: "Direito de Família", description: "Divórcio, guarda, pensão. Momento delicado que precisa de quem entende e respeita. Firmes na lei, sensíveis com você.", icon: "Heart" },
    ],
    testimonials: [
      { name: "João Carlos B.", text: "Meu ex-chefe me devia 3 anos de horas extras. O Melo brigou e eu recebi TUDO. Quando achei que não tinha mais jeito, eles mostraram que tinha.", role: "Causa trabalhista ganha", rating: 5 },
      { name: "Empresa TechSol Ltda", text: "Tínhamos um sócio que estava sugando a empresa. O Melo reestruturou tudo e hoje a empresa respira. Parceria jurídica de verdade.", role: "Cliente corporativo há 6 anos", rating: 5 },
      { name: "Mariana S.", text: "Meu ex não pagava pensão há 2 anos. Em 3 meses o Melo bloqueou a conta dele e eu comecei a receber. Justo é justo.", role: "Causa de família ganha", rating: 5 },
    ],
    phone: "(11) 3012-3456", whatsapp: "5511910376040", address: "Av. Paulista, 900 - Bela Vista, São Paulo - SP", email: "contato@meloadvocacia.com.br",
    navLinks: [{ label: "Início", href: "#" }, { label: "Sobre", href: "#sobre" }, { label: "Áreas de Atuação", href: "#servicos" }, { label: "Depoimentos", href: "#depoimentos" }, { label: "Contato", href: "#contato" }],
    stats: { years: "25+", clients: "1.800+", team: "14", rating: "4.9" },
  },
  "juridico-moderno": {
    slug: "juridico-moderno", companyName: "Contábil Nexus", tagline: "Sua contabilidade não pode ser um problema",
    primaryColor: "#2D5016", secondaryColor: "#F8FAF5",
    heroTitle: "Você abre a planilha e não entende nada? A gente resolve.", heroSubtitle: "Contabilidade em dia, impostos no prazo, funcionário com holerite correto. Você foca no seu negócio e a Nexus cuida do resto. Sem surpresa, sem multa, sem dor de cabeça burocrática.", heroCta: "Falar com Contador",
    aboutTitle: "Contabilidade que você entende", aboutText: "Contador que só entrega número não serve — você precisa entender pra onde seu dinheiro tá indo. A Nexus entrega relatório que qualquer empreendedor entende, paga seus impostos no prazo certo e ainda encontra formas legais de você pagar menos. MEI, ME ou EPP: a gente tira você da burocracia e coloca no lucro.",
    services: [
      { title: "Escrituração Contábil", description: "Tudo registrado, tudo em dia, tudo certinho. Relatório mensal que você ENTENDE. Sem complicação, sem juridiquês financeiro.", icon: "Calculator" },
      { title: "Declaração de Impostos", description: "DIRF, DCTF, SPED — a gente cuida de tudo. No prazo, sem erro, sem multa. Você dorme tranquilo.", icon: "FileText" },
      { title: "Abertura de Empresa", description: "Do CNPJ ao Alvará. A gente faz tudo e você só assina. MEI em 1 dia, ME em até 5 dias úteis. Sem correr atrás.", icon: "Building" },
      { title: "Consultoria Fiscal", description: "Tá pagando imposto demais? A gente analisa e encontra o regime ideal. Clientes economizam em média R$ 12 mil por ano. Legalmente.", icon: "TrendingUp" },
    ],
    testimonials: [
      { name: "Luciana F.", text: "Meu contador antigo entregava um monte de número que eu não entendia. A Nexus manda relatório com linguagem de gente. Finalmente sei quanto ganho de verdade.", role: "Cliente há 3 anos", rating: 5 },
      { name: "Pedro Henrique D.", text: "A consultoria fiscal me economizou R$ 15.600 por ano. LEGALMENTE. Eu tava jogando dinheiro fora no regime errado e ninguém me avisou.", role: "Cliente há 2 anos", rating: 5 },
      { name: "Fernanda O.", text: "Abri meu MEI em 1 dia sem sair de casa. A Nexus fez tudo pelo WhatsApp. Rápido, fácil e sem burocracia. Preço justo.", role: "Cliente há 1 ano", rating: 5 },
    ],
    phone: "(11) 3023-4567", whatsapp: "5511910376040", address: "Rua da Consolação, 567 - São Paulo - SP", email: "contato@contabilnexus.com.br",
    navLinks: [{ label: "Início", href: "#" }, { label: "Sobre", href: "#sobre" }, { label: "Serviços", href: "#servicos" }, { label: "Depoimentos", href: "#depoimentos" }, { label: "Contato", href: "#contato" }],
    stats: { years: "12+", clients: "600+", team: "6", rating: "4.8" },
  },
  "restaurante-quente": {
    slug: "restaurante-quente", companyName: "Brasa Viva", tagline: "Carne boa não precisa de segredo — só de brasa",
    primaryColor: "#DC2626", secondaryColor: "#1A1A1A",
    heroTitle: "Fome de carne de verdade? Chega mais.", heroSubtitle: "Picanha que derrete, costela que desmancha, maminha no ponto perfeito. Rodízio com 12 cortes premium e buffet que não te deixa com fome. Aquele almoço de domingo que sua família merece.", heroCta: "Reservar Mesa",
    aboutTitle: "Churrasco que faz justiça ao nome", aboutText: "Tem churrascaria que serve carne dura com cara de churrasco. Aqui não. A Brasa Viva existe há 19 anos porque a carne é boa de verdade. Cortes selecionados de produtores que a gente conhece pelo nome, brasa de carvão na hora e mestre churrasqueiro que sabe o ponto de cada corte. O rodízio é farto, o buffet é completo e o preço é honesto. Venha uma vez — você volta.",
    services: [
      { title: "Rodízio de Churrasco", description: "12+ cortes de carne na brasa. Picanha, costela, maminha, alcatra, fraldinha... tudo passando na sua mesa. Sem limitação.", icon: "Flame" },
      { title: "Buffet Completo", description: "Salada fresca, farofa crocante, pão de queijo, queijo na brasa e sobremesa artesanal. Comida de verdade que acompanha a carne.", icon: "Utensils" },
      { title: "Festas e Eventos", description: "Aniversário, reunião de família, confraternização. Espaço privativo com menu especial e atendimento exclusivo pra seu grupo.", icon: "PartyPopper" },
      { title: "Carta de Vinhos", description: "Mais de 40 rótulos nacionais e importados escolhidos a dedo. Sommelier pra te ajudar a escolher o vinho certo pra cada carne.", icon: "Wine" },
    ],
    testimonials: [
      { name: "Roberto S.", text: "A picanha da Brasa Viva é VICIANTE. Derrete na boca. Já levei a família toda e virou nosso lugar de domingo. Preço justo pra qualidade absurda.", role: "Cliente há 5 anos", rating: 5 },
      { name: "Amanda T.", text: "Fiz meu aniversário no espaço de eventos. Comida de primeira, atendimento nota 10 e meus convidados falaram do churrasco por semanas. Recomendo demais.", role: "Feu evento no local", rating: 5 },
      { name: "Carlos M.", text: "Rodízio que é rodízio de verdade. Cada corte que vem é melhor que o anterior. Saio comendo demais toda vez e não me arrependo.", role: "Cliente há 3 anos", rating: 5 },
    ],
    phone: "(11) 3034-5678", whatsapp: "5511910376040", address: "Rua Domingos de Moraes, 890 - Vila Mariana, São Paulo - SP", email: "contato@brasaviva.com.br",
    navLinks: [{ label: "Início", href: "#" }, { label: "Sobre", href: "#sobre" }, { label: "Cardápio", href: "#servicos" }, { label: "Depoimentos", href: "#depoimentos" }, { label: "Contato", href: "#contato" }],
    stats: { years: "19+", clients: "5.000+", team: "25", rating: "4.9" },
  },
  "restaurante-minimalista": {
    slug: "restaurante-minimalista", companyName: "Mirin", tagline: "Sushi que faz justiça ao Japão",
    primaryColor: "#8B7355", secondaryColor: "#F5F0EB",
    heroTitle: "Peixe fresco não manda aviso — chega todo dia.", heroSubtitle: "Atum bluefin, salmão selvagem, uni de Hokkaido. Sushi cortado na hora pelo chef formado em Tóquio. Menu omakase de 12 etapas que é uma viagem sem sair da cadeira. Ramen com caldo que cozinha 18 horas.", heroCta: "Reservar Experiência",
    aboutTitle: "Do Japão pra sua mesa — sem atalho", aboutText: "O Mirin não é mais um restaurante japonês com salmão congelado e cream cheese. Nosso chef estudou no Tokyo Sushi Academy e trouxe a técnica, o respeito ao ingrediente e a obsessão pelo detalhe. Peixe importado semanalmente, arroz temperado na hora e faca afiada que faz o corte perfeito. O ambiente foi pensado pra você focar no que importa: o sabor.",
    services: [
      { title: "Sushi e Sashimi Premium", description: "Peças nobres cortadas na hora. Atum bluefin, salmão selvagem, uni, ovas. Nada congelado, nada enlatado. Pescado fresco toda semana.", icon: "Fish" },
      { title: "Menu Omakase", description: "12 etapas que o chef escolhe pra você. Uma viagem pelos sabores da estação. Experiência gastronômica que você não esquece.", icon: "ChefHat" },
      { title: "Ramen Artesanal", description: "Caldo de 18 horas, noodle feito na casa, chashu derretido. Não é miojo com caldo — é ramem de verdade. Viciante.", icon: "Flame" },
      { title: "Harmonização com Saquê", description: "30+ rótulos de saquê e whisky japonês. Cada drink escolhido pra potencializar o sabor do prato. Orientação do sommelier.", icon: "Wine" },
    ],
    testimonials: [
      { name: "Yuki T.", text: "Sou nipo-brasileira e esse é o único lugar em SP que me faz sentir no Japão. O niguiri é perfeito — arroz na temperatura certa, peixe na espessura certa. Choro de emoção.", role: "Cliente há 3 anos", rating: 5 },
      { name: "Marcelo R.", text: "O omakase foi a melhor experiência gastronômica da minha vida. Cada prato era uma surpresa melhor que a anterior. Vale cada centavo.", role: "Cliente há 1 ano", rating: 5 },
      { name: "Ana C.", text: "O ramen vicia. Caldo profundo, noodle al dente, chashu que derrete. Volto toda semana e não me envergonho. É o melhor de SP, sem discussão.", role: "Cliente há 2 anos", rating: 5 },
    ],
    phone: "(11) 3045-6789", whatsapp: "5511910376040", address: "Rua Bela Cintra, 456 - Consolação, São Paulo - SP", email: "contato@mirin.com.br",
    navLinks: [{ label: "Início", href: "#" }, { label: "Sobre", href: "#sobre" }, { label: "Menu", href: "#servicos" }, { label: "Depoimentos", href: "#depoimentos" }, { label: "Contato", href: "#contato" }],
    stats: { years: "7+", clients: "900+", team: "8", rating: "4.9" },
  },
  "pet-lovers": {
    slug: "pet-lovers", companyName: "Pet Lovers", tagline: "Seu pet é da família — trata como tal",
    primaryColor: "#E8735A", secondaryColor: "#FFF5F0",
    heroTitle: "Seu cachorro treme quando chega na porta do pet shop?", heroSubtitle: "Aqui não. A Pet Lovers é o lugar que seu pet puxa você pra entrar. Banho sem gaiola, tosa com paciência, veterinário que fala com ele antes de examinar. Ração premium e adestramento que funciona. Tudo num lugar só.", heroCta: "Agendar Banho e Tosa",
    aboutTitle: "Pet shop que seu pet ama — e você confia", aboutText: "A gente sabe que pet é filho. Por isso a Pet Lovers não é um pet shop comum: é o lugar onde seu dog puxa a coleira pra entrar. Banho sem gaiola de espera, tosadores que tratam com carinho, ração que você não encontra em mercado e adestramento com método positivo. Seu pet sai feliz e você sai tranquilo. Há 7 anos assim.",
    services: [
      { title: "Banho e Tosa", description: "Sem gaiola de espera. Banho com produto premium e tosa personalizada pro seu pet. Ele sai lindo E feliz. Até os que odeiam banho gostam aqui.", icon: "Sparkles" },
      { title: "Ração e Produtos", description: "As melhores marcas que o supermercado não tem. Ração premium, snacks naturais e brinquedos que duram. Orientação nutricional grátis.", icon: "ShoppingBag" },
      { title: "Veterinário", description: "Consulta, vacina e exame sem estresse pro pet. Veterinário parceiro que atende com calma e cuidado. Preventivo e emergência.", icon: "Heart" },
      { title: "Adestramento", description: "Seu dog puxa na guia, pula nas visitas ou destrói o sofá? Método positivo, sem violência. Resultado real em 4 semanas.", icon: "Dog" },
    ],
    testimonials: [
      { name: "Fernanda M.", text: "Meu yorkshire TREPEDIA na porta da Pet Lovers. Em outro pet shop ele tremia. Aqui é outro mundo. A equipe é maravilhosa com ele.", role: "Cliente há 3 anos", rating: 5 },
      { name: "Rafael S.", text: "Meu filhote de pastor alemão era um terror. 4 semanas de adestramento e ele obedece comandos, não puxa na guia e não pula mais nas visitas. Funciona MESMO.", role: "Cliente há 1 ano", rating: 5 },
      { name: "Juliana P.", text: "Ração que o supermercado não tem, brinquedo que não quebra e gente que realmente gosta de animal. É o único lugar que levo meus gatos.", role: "Cliente há 2 anos", rating: 5 },
    ],
    phone: "(11) 3567-8901", whatsapp: "5511910376040", address: "Rua Voluntários da Pátria, 567 - Santana, São Paulo - SP", email: "contato@petlovers.com.br",
    navLinks: [{ label: "Início", href: "#" }, { label: "Sobre", href: "#sobre" }, { label: "Serviços", href: "#servicos" }, { label: "Depoimentos", href: "#depoimentos" }, { label: "Contato", href: "#contato" }],
    stats: { years: "7+", clients: "2.500+", team: "12", rating: "4.9" },
  },
  "pet-vet": {
    slug: "pet-vet", companyName: "Vet Center", tagline: "Quando seu pet precisa, a gente tá aqui",
    primaryColor: "#2D7D46", secondaryColor: "#F0F8F0",
    heroTitle: "Seu pet tá estranho e você não sabe por quê?", heroSubtitle: "Não espera piorar. Na Vet Center, a gente examina com calma, explica o que tá acontecendo e apresenta o tratamento. Sem empurrar procedimento, sem assustar. Emergência 24h pra quando a vida do seu pet não pode esperar.", heroCta: "Agendar Consulta",
    aboutTitle: "Veterinária que respeita você e seu pet", aboutText: "Seu pet não sabe falar, mas sabe demonstrar quando tá mal. A Vet Center existe pra ler esses sinais e agir rápido. Exame completo, diagnóstico preciso e tratamento que funciona — tudo explicado de forma que você entenda. Sem jogar termo técnico pra impressionar, sem empurrar exame desnecessário. Há 12 anos salvando vidas com competência e honestidade.",
    services: [
      { title: "Consultas e Check-ups", description: "Exame completo de olhos, ouvidos, pele, coração e mais. Checamos TUDO. Prevenção é mais barata que emergência.", icon: "Microscope" },
      { title: "Vacinação", description: "Programa completo com vacinas importadas. Carteirinha digital no celular. Nunca mais esqueça a data da vacina.", icon: "Shield" },
      { title: "Cirurgias", description: "Centro cirúrgico equipado e equipe anestésica dedicada. Castração, tumor, ortopedia. Seu pet em boas mãos.", icon: "Heart" },
      { title: "Emergência 24h", description: "Seu pet passou mal de madrugada? Liga. Estamos aqui 24 horas. Porque emergência não marca hora.", icon: "Zap" },
    ],
    testimonials: [
      { name: "Carla R.", text: "Meu gato quase morreu de madrugada. Liguei pro Vet Center e em 20 minutos já estava sendo atendido. Salvaram a vida dele. Não tenho palavras pra agradecer.", role: "Cliente há 4 anos", rating: 5 },
      { name: "Marcos T.", text: "O programa de vacinação é perfeito. Recebo lembrete no WhatsApp e nunca mais esqueci. Os vets são super pacientes com meus dois doidos.", role: "Cliente há 2 anos", rating: 5 },
      { name: "Ana L.", text: "Castração da minha cadela: cirurgia perfeita, recuperação rápida e acompanhamento pós até ela tá 100%. Gente que se importa de verdade.", role: "Cliente há 1 ano", rating: 5 },
    ],
    phone: "(11) 3678-9012", whatsapp: "5511910376040", address: "Rua Pamplona, 789 - Jardim Paulista, São Paulo - SP", email: "contato@vetcenter.com.br",
    navLinks: [{ label: "Início", href: "#" }, { label: "Sobre", href: "#sobre" }, { label: "Serviços", href: "#servicos" }, { label: "Depoimentos", href: "#depoimentos" }, { label: "Contato", href: "#contato" }],
    stats: { years: "12+", clients: "3.200+", team: "9", rating: "4.9" },
  },
  "imob-housi": {
    slug: "imob-housi", companyName: "Housi", tagline: "Imóvel bom não fica no mercado por muito tempo",
    primaryColor: "#1A1A2E", secondaryColor: "#E94560",
    heroTitle: "O apartamento dos seus sonhos vai embora enquanto você pensa.", heroSubtitle: "Imóveis premium em São Paulo que saem em dias. Compra, venda e locação com curadoria de alto padrão. Atendimento exclusivo que entende o que você quer antes de você explicar.", heroCta: "Ver Imóveis Disponíveis",
    aboutTitle: "Imobiliária que entende que tempo é dinheiro", aboutText: "Imóvel bom some do mercado em 48 horas. Se você tá vendo o mesmo anúncio há semanas, não é porque é ruim — é porque ninguém com boa intenção tá te mostrando o que realmente vale a pena. A Housi curadoria cada imóvel antes de colocar no portfólio. Se tá aqui, é porque vale. Nosso consultor entende seu perfil e te mostra no máximo 5 opções — as certas.",
    services: [
      { title: "Compra e Venda", description: "Análise de mercado, negociação agressiva e acompanhamento do começo ao fim. Você paga o preço justo — nem mais, nem menos.", icon: "Key" },
      { title: "Locação Premium", description: "Portfolio curado de imóveis para locação. Contrato transparente, vistoria detalhada e suporte jurídico incluso. Sem dor de cabeça.", icon: "Home" },
      { title: "Avaliação de Imóveis", description: "Quanto vale o seu imóvel de verdade? Laudo técnico baseado em mercado real, não em achismo. Dados, não palpite.", icon: "BarChart3" },
      { title: "Consultoria de Investimento", description: "Onde comprar pra valorizar? Qual o retorno real do aluguel? Investimento imobiliário com cabeça, não com emoção.", icon: "TrendingUp" },
    ],
    testimonials: [
      { name: "Rodrigo M.", text: "A Housi encontrou meu apartamento em 10 dias. Mostrei o que eu queria uma vez e o consultor mandou 3 opções perfeitas. Comprei a primeira. Rápido e certeiro.", role: "Comprou apartamento", rating: 5 },
      { name: "Fernanda L.", text: "Vendi meu imóvel pelo valor MÁXIMO de mercado. A consultoria deles fez toda a diferença na negociação. Recomendo de olhos fechados.", role: "Vendeu imóvel", rating: 5 },
      { name: "Casal Almeida", text: "Primeiro aluguel e estávamos perdidos. A Housi explicou tudo, fez o contrato e acompanhou cada passo. Processo tranquilo do início ao fim.", role: "Alugaram apartamento", rating: 5 },
    ],
    phone: "(11) 3789-0123", whatsapp: "5511910376040", address: "Av. Faria Lima, 3456 - Itaim Bibi, São Paulo - SP", email: "contato@housi.com.br",
    navLinks: [{ label: "Início", href: "#" }, { label: "Sobre", href: "#sobre" }, { label: "Imóveis", href: "#servicos" }, { label: "Depoimentos", href: "#depoimentos" }, { label: "Contato", href: "#contato" }],
    stats: { years: "8+", clients: "1.500+", team: "20", rating: "4.9" },
  },
  "imob-lar": {
    slug: "imob-lar", companyName: "Lar Doce Lar", tagline: "Ache sua casa — não só um imóvel",
    primaryColor: "#8B6914", secondaryColor: "#FFFBEB",
    heroTitle: "Tá cansado de ver imóvel que parece bom nas fotos e é ruim ao vivo?", heroSubtitle: "Na Lar Doce Lar, a gente visita antes de te mostrar. Se o imóvel é bom, tá no nosso portfólio. Se não é, a gente te diz na cara. 20 anos de honestidade que nenhuma plataforma de anúncio tem.", heroCta: "Conhecer Imóveis",
    aboutTitle: "Imobiliária que te acompanha como família", aboutText: "Comprar ou alugar imóvel é uma das decisões mais importantes da sua vida. Na Lar Doce Lar, você não é um número — é uma família que merece atenção. A gente escuta, entende e mostra opções que realmente fazem sentido. Sem te empurrar imóvel que não serve, sem mentir na descrição, sem sumir depois da assinatura. Há 20 anos construindo lares de verdade.",
    services: [
      { title: "Compra e Venda", description: "Do primeiro contato até as chaves na mão. A gente acompanha cada passo, negocia por você e garante que o negócio seja seguro.", icon: "Key" },
      { title: "Locação", description: "Imóveis visitados e aprovados por nós. Contrato claro, vistoria justa e suporte durante todo o contrato.", icon: "Home" },
      { title: "Orientação de Financiamento", description: "Qual banco aprova mais? Qual a melhor taxa? A gente te conecta com os parceiros certos pra seu perfil.", icon: "Landmark" },
      { title: "Avaliação Justa", description: "Quanto vale o seu imóvel? Avaliação honesta baseada em dados reais. Sem inflacionar pra ganhar comissão.", icon: "BarChart3" },
    ],
    testimonials: [
      { name: "Família Santos", text: "Com 3 filhos, precisávamos de uma casa que realmente servisse. A Lar Doce Lar fez questão de mostrar os pontos bons E os ruins de cada imóvel. Honestidade rara.", role: "Compraram casa", rating: 5 },
      { name: "Dona Maria", text: "Vendi minha casa com eles. O valor que avaliaram era REAL — não inflacionado. Vendi em 3 semanas. Respeito e honestidade do começo ao fim.", role: "Vendeu imóvel", rating: 5 },
      { name: "Lucas P.", text: "Primeiro aluguel, zero experiência. A Lar Doce Lar explicou tudo com paciência, sem julgamento. Me senti seguro pra assinar.", role: "Alugou apartamento", rating: 5 },
    ],
    phone: "(11) 3890-1234", whatsapp: "5511910376040", address: "Rua Conselheiro Nébias, 456 - Campos Elíseos, São Paulo - SP", email: "contato@lardocelar.com.br",
    navLinks: [{ label: "Início", href: "#" }, { label: "Sobre", href: "#sobre" }, { label: "Imóveis", href: "#servicos" }, { label: "Depoimentos", href: "#depoimentos" }, { label: "Contato", href: "#contato" }],
    stats: { years: "20+", clients: "3.000+", team: "15", rating: "4.8" },
  },
  "fitness-iron": {
    slug: "fitness-iron", companyName: "Iron Fit", tagline: "Desculpa não transforma corpo — treino sim",
    primaryColor: "#FF2E2E", secondaryColor: "#1A1A1A",
    heroTitle: "Cansado de começar academia e parar em 2 meses?", heroSubtitle: "Na Iron Fit, o personal te liga quando você falta. Equipamento de primeira, treino montado pro SEU corpo e comunidade que te puxa pra cima nos dias que você quer desistir. Sem enrolação, sem papinho — só resultado.", heroCta: "Começar a Treinar",
    aboutTitle: "Academia que te transforma — e te faz voltar", aboutText: "A verdade? 80% das pessoas param de treinar nos primeiros 3 meses. Na Iron Fit, a taxa de permanência é 3x maior. Sabe por quê? Porque o personal te liga quando falta, o treino muda antes de ficar chato e a comunidade te acolhe desde o primeiro dia. Não importa se você tá começando ou se já levanta 100kg — aqui tem lugar e respeito pra todo mundo. Há 10 anos transformando corpos e mentalidades.",
    services: [
      { title: "Musculação", description: "Equipamento Hammer e Life Fitness, treino personalizado e professor na sala. Nada de academia lotada sem ninguém pra te ajudar.", icon: "Dumbbell" },
      { title: "Personal Trainer", description: "Acompanhamento individual. Treino montado pro SEU corpo, SEU objetivo e SEU ritmo. 100% focado em você.", icon: "User" },
      { title: "CrossFit", description: "Box exclusivo com WOD diário e coaching qualificado. Comunidade que treina junto e empurra junto. Viciante no bom sentido.", icon: "Flame" },
      { title: "Luta e MMA", description: "Muay Thai, Jiu-Jitsu e MMA com professores que lutam de verdade. Aprenda a se defender enquanto queima caloria.", icon: "Activity" },
    ],
    testimonials: [
      { name: "Bruno S.", text: "Em 6 meses perdi 20kg. Os personals da Iron Fit não deixam você desistir. Nos dias que eu queria ficar em casa, o pessoal me puxava. Resultado real.", role: "Aluno há 1 ano", rating: 5 },
      { name: "Amanda K.", text: "O CrossFit mudou minha vida. A comunidade é INSANA. Nos dias que quero desistir, o pessoal me puxa. Treino não é sacrifício aqui — é diversão.", role: "Aluna há 2 anos", rating: 5 },
      { name: "Ricardo L.", text: "Equipamento de primeiro, professor presente e ambiente limpo. Parece óbvio, mas a maioria das academias não tem isso. A Iron Fit tem e cobra justo.", role: "Aluno há 3 anos", rating: 5 },
    ],
    phone: "(11) 3901-2345", whatsapp: "5511910376040", address: "Av. Rebouças, 1234 - Pinheiros, São Paulo - SP", email: "contato@ironfit.com.br",
    navLinks: [{ label: "Início", href: "#" }, { label: "Sobre", href: "#sobre" }, { label: "Modalidades", href: "#servicos" }, { label: "Depoimentos", href: "#depoimentos" }, { label: "Contato", href: "#contato" }],
    stats: { years: "10+", clients: "2.000+", team: "18", rating: "4.9" },
  },
  "fitness-zen": {
    slug: "fitness-zen", companyName: "Zen Studio", tagline: "Seu corpo pede paz — dê a ele",
    primaryColor: "#5B7C6F", secondaryColor: "#F0F5F2",
    heroTitle: "Sua colina dói, sua mente acelera e você não para nunca.", heroSubtitle: "Yoga que alonga de verdade, pilates que fortalece sem estresse e meditação que silencia a bagunça na sua cabeça. No Zen Studio, você respira, se move e sai outro. Primeira aula experimental é por nossa conta.", heroCta: "Agendar Aula Grátis",
    aboutTitle: "Um lugar pra respirar de verdade", aboutText: "Você acorda cansado, vai dormir ansioso e no meio do dia já quer que acaba. O Zen Studio existe pra ser o contrário de tudo isso. Aqui, o celular fica fora, o relógio não importa e o único compromisso é com você mesmo. Instrutores que praticam há anos, aulas pra todos os níveis e ambiente que te faz esquecer o caos lá fora. Funciona há 5 anos pra quem precisa funcionar melhor.",
    services: [
      { title: "Yoga Vinyasa", description: "Fluido e desafiador. Conecta movimento e respiração pra flexibilidade, força e presença. Pra quem acha que yoga é só meditação.", icon: "Activity" },
      { title: "Pilates Clássico", description: "Método Joseph Pilates original com aparelho. Fortalece o core, corrige a postura e acaba com a dor nas costas. Resultado real.", icon: "Flower2" },
      { title: "Meditação Guiada", description: "Sua mente não para? A gente te ensina. Técnicas de mindfulness que reduzem ansiedade e aumentam foco. Funciona desde a primeira sessão.", icon: "Brain" },
      { title: "Yoga Restaurativo", description: "Posturas passivas com cobertor e bloco. Relaxamento PROFUNDO. Pra quem tá exausto e precisa resetar. Você sai flutuando.", icon: "Heart" },
    ],
    testimonials: [
      { name: "Camila F.", text: "Eu tinha dor nas costas há 5 anos. Em 2 meses de pilates no Zen Studio, acabou. Acabou! Eu não acreditei. As professoras são incríveis.", role: "Aluna há 2 anos", rating: 5 },
      { name: "Paulo R.", text: "A meditação mudou minha relação com ansiedade. Não é misticismo — é técnica. Aprendi a respirar e a colocar a mente no lugar. Funciona.", role: "Aluno há 1 ano", rating: 5 },
      { name: "Isabella M.", text: "O yoga restaurativo é meu refúgio. Toda quarta eu entro estressada e saio flutuando. Se eu pudesse, ia todo dia. Lugar de paz de verdade.", role: "Aluna há 8 meses", rating: 5 },
    ],
    phone: "(11) 4012-3456", whatsapp: "5511910376040", address: "Rua Girassol, 321 - Vila Madalena, São Paulo - SP", email: "contato@zenstudio.com.br",
    navLinks: [{ label: "Início", href: "#" }, { label: "Sobre", href: "#sobre" }, { label: "Aulas", href: "#servicos" }, { label: "Depoimentos", href: "#depoimentos" }, { label: "Contato", href: "#contato" }],
    stats: { years: "5+", clients: "800+", team: "7", rating: "4.9" },
  },
};
